# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ccf2d7da69f9d7d2754523d380715457f2aea95d79402254d7f5bb9ff30befbfcb47a736ce5a934dc11ce1b0ddce8df410a6e7ee62bcc5b63e95bbaf396829

test:
  secret_key_base: e3701f06ac38977deacead793bb5ccf41e5545142bf3ebb012cdeb93d9d2b77e23429e878d9b2c6cf42cf97fccbad38b69da077766c87b3588d1c5eaa6dc0eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
